### ISSUE TITLE
Can not install the docker required

### ISSUE THREAD

**Issue by LPY1219** [NVlabs/motion-policy-networks#10]
When I try to install the docker according to the README,there are some errors that I can not under stand
![image](https://user-images.githubusercontent.com/80994085/219828413-bc48e990-71d8-488d-a4ce-1ef647c13987.png)

**Comment by fishbotics** [comment]
Could you try the following?

First, remove this line: https://github.com/NVlabs/motion-policy-networks/blob/3c3a632d238622477f29347dfd7b6df34bfe0d18/docker/Dockerfile#L152

Then add an additional `RUN` command in the docker (perhaps here: https://github.com/NVlabs/motion-policy-networks/blob/3c3a632d238622477f29347dfd7b6df34bfe0d18/docker/Dockerfile#L154). This command should say:

`RUN git clone https://github.com/fishbotics/pointnet2_ops && cd pointnet2_ops && git checkout v3.2.0 && python3 setup.py install`

I'm wondering if the method of doing version comparisons broke for a new version of Pip.

**Comment by yanghouxue** [comment]
I have the same problem. I suspect it is the problem of the installed version of torch. Can you tell me which version of torch is installed in your environment

**Comment by fishbotics** [comment]
I think I fixed the issue over in Robofin--it seems that version specification for setuptools does not support `+` characters anymore. If you try rebuilding now, it should work.

**Comment by fishbotics** [comment]
This seems to work on my end so I will close the issue. Please re-open if it's not fixed for you.

**Comment by LPY1219** [comment]
Thanks for your help,It also works on my machine.By the way,could you please provide the code of the real-robot experiment?I am trying to deploy it on my Franka @fishbotics

**Comment by LPY1219** [comment]
Meanwhile,I can run the code after the above modification,but it seems that I have to execute "pip install -e ." in the directory of "pointnet2_ops" to make the program find that module.
