### ISSUE TITLE
how do I install ompl package

### ISSUE THREAD

**Issue by venishkrishna** [NVlabs/motion-policy-networks#11]

**Comment by fishbotics** [comment]
This is illustrated in the Dockerfile in the following lines: https://github.com/NVlabs/motion-policy-networks/blob/main/docker/Dockerfile#L43-L89

If you want to install OMPL outside of this docker environment, you can also follow the instructions from the OMPL website. They have a very helpful download script: https://ompl.kavrakilab.org/download.html
