### ISSUE TITLE
Problem when running run_inference

### ISSUE THREAD

**Issue by rangfeng1** [NVlabs/motion-policy-networks#15]
When running run_inference ，Where is corl_2022_hybrid_expert_checkpoint.ckpt.If using a weight file, it will be displayed at runtime 
line 469, in <module>
    problems = pickle.load(f)
ModuleNotFoundError: No module named 'mpinets'

**Comment by fishbotics** [comment]
This seems like your Python path isn't set correctly. Just to confirm, can you please open the Python REPL (within the environment, docker or otherwise, where you're getting this error) and try importing `mpinets`? If it's not found, you probably just need to put it in your `PYTHONPATH`

**Comment by fishbotics** [comment]
I will close this issue, but please re-open if you're still having issues.
