### ISSUE TITLE
AttributeError: module 'pointnet2_ops._ext' has no attribute 'furthest_point_sampling'

### ISSUE THREAD

**Issue by rangfeng1** [NVlabs/motion-policy-networks#17]
When I run run_train ,I get the problem.

**Comment by fishbotics** [comment]
This probably means that pointnet2_ops did not install correctly. Are you using the Docker? Did you get any errors when installing this package?

**Comment by rangfeng1** [comment]
No, I didn't use docker. When installing docker, I got stuck at this step and couldn't proceed. So I used anaconda, and I tried to install pointnet2_ops._ext again.

**Comment by rangfeng1** [comment]
When running the installation of pointnet2_ops, I encountered the problem that there is no header file：
fatal error: cusolverDn.h: 没有那个文件或目录
 #include <cusolverDn.h>
          ^~~~~~~~~~~~~~
compilation terminated.
error: command '/usr/bin/gcc' failed with exit code 1

**Comment by rangfeng1** [comment]
I have solve it ,thanks

**Comment by fishbotics** [comment]
@rangfeng1 , can you explain what you did to find the solution?

**Comment by rangfeng1** [comment]
ok，I just update the navi-sim.
