### ISSUE TITLE
I have a problem about how to use the run_inference to  Custom Issues.Can you give me a example?

### ISSUE THREAD

**Issue by rangfeng1** [NVlabs/motion-policy-networks#22]
I have problem about how to use the run_inference to  Custom Issues.Can you give me a example?Secondly, how to convert the problem into a pkl file.

**Comment by fishbotics** [comment]
I suggest looking at how these pickle files are generated: https://github.com/NVlabs/motion-policy-networks/blob/main/mpinets/data_pipeline/gen_data.py#L927

It should be fairly straightforward to create a custom scene, either made of primitives or a point cloud. The pickle files have a specific nested structure that is expected by `run_inference` but the problems themselves are of this type: https://github.com/NVlabs/motion-policy-networks/blob/main/mpinets/types.py#L35

**Comment by fishbotics** [comment]
I will close this issue but please re-open if you run into further trouble.
