### ISSUE TITLE
How should I install the ompl in my anaconda？

### ISSUE THREAD

**Issue by rangfeng1** [NVlabs/motion-policy-networks#23]
Hello，Do you know how should I install the ompl in my anaconda.

**Comment by fishbotics** [comment]
You likely have to build it from scratch and point to the correct Python binary when you build. That said, I don't use Anaconda, so I probably am not the best person to ask. If you're stuck, you should ask for advice in either the OMPL Repository or the OMPL mailing list.

**Comment by fishbotics** [comment]
I will close this because the discussion was moved to here: https://github.com/ompl/ompl/issues/1019
