### ISSUE TITLE
Problem when execute run_inference.py with use_depth = True

### ISSUE THREAD

**Issue by STAY-Melody** [NVlabs/motion-policy-networks#32]
Hi!

Executing `run_inference.py` with `use_depth = True` seems to trigger the input error in this [line](https://github.com/fishbotics/robofin/blob/a8b2362ad58f213db7d78c96698694ed579f2473/robofin/bullet.py#L523C9-L523C23), in which the correct input should be `quaternion=` instead of `quat=`. 

However, I found that the input syntax error has been corrected in the [main branch of robofin](https://github.com/fishbotics/robofin/blob/a43497f14a4eacda263979827bbdbf7925eae3c9/robofin/bullet.py#L675). So, why not update the dockerfile to install the `main` branch instead of `v0.0.1`?

Thanks!

**Comment by fishbotics** [comment]
Thanks for finding this bug! I fixed it in the v0.0.1 branch in robofin, so the Dockerfile should now install a version of that package without that issue.

You raise a good point about switching to the main branches. The reason why I pinned the version at a particular branch is that I want this library to be a reproducible copy of the work published in the Motion Policy Networks work and I don't want the performance to drift too far from the performance at the time of that publication. Robofin is a toolkit I'm actively developing and has an unstable API on the main branch. I suspect that switching to the main branch would both change the performance of this library and cause a lot of headaches as the API changes over time.

If you're interested in using the newer versions of robofin (or geometrout or atob), feel free to comment over on those repos and I can help you get set up.
