### ISSUE TITLE
Return value of verify_has_solvable_problems function in gen_data.py

### ISSUE THREAD

**Issue by zichunxx** [NVlabs/motion-policy-networks#33]
Hi! @fishbotics 

Whether the return value of [`verify_has_solvable_problems`](https://github.com/NVlabs/motion-policy-networks/blob/6e3cf2d9701f01795a9f27da76a9df40b27bc3d5/mpinets/data_pipeline/gen_data.py#L637) should be modified to `success` to ensure that `gen_valid_env` function can keep running until a solvable environment is found. Is this a typo error?

Thanks!

**Comment by fishbotics** [comment]
I might be misunderstanding your question, but the purpose of part of the function is to keep trying to generate environments until one succeeds. Success means that 1) an environment is generated 2) there is at least one problem (according to the environments problem specification) in that environment (a reachable pose with a collision free IK solution), and that this one problem has a valid path. The line you linked checks whether this problem has a satisfiable path. If it doesn't, the loop generates a new environment.

I'm not sure what typo you are talking about, but you could post a proposed solution and I can take a look.

**Comment by fishbotics** [comment]
Oh wow, you're totally right. I will update that.
