### ISSUE TITLE
Render franka with colors

### ISSUE THREAD

**Issue by zichunxx** [NVlabs/motion-policy-networks#34]
Hi!

Why not choose to render Franka arm with black and white colors with original files in bullet, like Figure 1 in your paper?

This is just a minor suggestion to enhance the visualization. 

Would it be possible to consider changes to the relevant files in `robofin`?

Thanks!

**Comment by fishbotics** [comment]
Hi @zichunxx 

Can you file this issue in robofin? The goal of the MPiNets repo is to be frozen as it was for the paper (which is why it's pinned at a specific version of robofin) but robofin is a living project and I'd be happy to make that change.

Thanks!
