### ISSUE TITLE
When building the docker, <none> is displayed where the label "mpinets" should be.

### ISSUE THREAD

**Issue by ZhangYue1226** [NVlabs/motion-policy-networks#4]
Hi! There are two confuses I wanna figure out:

First, when I followed your step to clone the repo using: git clone https://gitlab-master.nvidia.com/srl/motion-policy-networks , why can't this link be found?

Second, when building the docker, why is <none> displayed in the terminal where the tag "mpinets" should be?

Looking forward to your answer! Thank you!

**Comment by doshininad** [comment]
@ZhangYue1226 I agree to the first point. The link to the repo is not working. I have the same issue.
Did not understood the second question.

**Comment by adithyamurali** [comment]
The repo link has been fixed aebee854df1c94026d8586eae48f08573a329986

**Comment by fishbotics** [comment]
Hi @ZhangYue1226 , thanks for pointing these issues out. 

For your second question, can you post a picture of the behavior you're seeing and explain what you expect?

**Comment by fishbotics** [comment]
I'm going to close this issue because it's been hanging for 3 months. @ZhangYue1226 , feel free to reopen it if you're still having issues.
