### ISSUE TITLE
creating a problem 

### ISSUE THREAD

**Issue by venishkrishna** [NVlabs/motion-policy-networks#9]
can please explain to create our own problem pickle file.

**Comment by fishbotics** [comment]
You should take a look at the function we use to generate these problem pickle files. Here is the one used to generate the task oriented pickle files: https://github.com/NVlabs/motion-policy-networks/blob/3c3a632d238622477f29347dfd7b6df34bfe0d18/mpinets/data_pipeline/gen_data.py#L814

The structure of the files is:

```
environment_name = "my new environment"
{
  environment_name: {
    'task_oriented': [],
    'neutral_start': [],
    'neutral_goal': [],  
  }
}
```
Each of those lists above should be lists of the `PlanningProblem` class, which is defined here: https://github.com/NVlabs/motion-policy-networks/blob/3c3a632d238622477f29347dfd7b6df34bfe0d18/mpinets/types.py#L1

I will close this but please re-open if you need more help!
